steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/excel-addin-react', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/excel-addin-react']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'excel-addin-react'
      - '--image=gcr.io/$PROJECT_ID/excel-addin-react'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/excel-addin-react'
