steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: 'gcr.io/buildpacks/builder'
    args: [
      'pack', 'build', 'gcr.io/$PROJECT_ID/excel-addin-react',
      '--builder', 'gcr.io/buildpacks/builder:v1'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'excel-addin-react'
      - '--image=gcr.io/$PROJECT_ID/excel-addin-react'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
